"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { customers, money, percent, products, sdg } from "@/lib/finance";
import { AuthPanel, SessionStrip, authorizedFetch, type Identity } from "@/lib/auth-client";
type Line = { id: string; product_id: string; quantity: number; unit_price_usd_cents: number; discount_usd_cents: number; line_total_usd_cents: number; discount_percentage_basis_points: number };
type Order = { id: string; customer_id: string; created_at: string; exchange_rate_sdg_per_usd: number; subtotal_usd_cents: number; discount_usd_cents: number; total_usd_cents: number; total_sdg: number; order_lines: Line[]; audit_events: { created_at: string; event_type: string; details: Record<string, unknown> }[] };
export default function OrderDetail({ params }: { params: Promise<{ id: string }> }) { return <AuthPanel>{identity => <Detail identity={identity} params={params} />}</AuthPanel>; }
function Detail({ identity, params }: { identity: Identity; params: Promise<{ id: string }> }) {
  const [order, setOrder] = useState<Order | null>(null);
  const [rate, setRate] = useState<number | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { params.then(async ({ id }) => { try { const [orderResponse, rateResponse] = await Promise.all([authorizedFetch(`/api/orders/${id}`), authorizedFetch("/api/rate")]); const orderData = await orderResponse.json(); if (!orderResponse.ok) throw new Error(orderData.error); setOrder(orderData); const rateData = await rateResponse.json(); if (rateResponse.ok) setRate(rateData.rate); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load order."); } finally { setLoaded(true); } }); }, [params]);
  async function setTodayRate() { try { const response = await authorizedFetch("/api/rate", { method: "PATCH", body: JSON.stringify({ rate: 9000 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRate(data.rate); setMessage("Current rate updated. Historical order remains unchanged."); } catch (e) { setMessage(e instanceof Error ? e.message : "Rate update failed."); } }
  if (!loaded) return <div className="page">Loading order…</div>;
  if (!order) return <div className="page"><h1>Order unavailable</h1><p>{message || "Order not found."}</p><Link href="/orders">View orders</Link></div>;
  return <div className="page"><div className="page-heading"><div><div className="eyebrow"><Link href="/orders">ORDERS</Link> / SAVED ORDER</div><h1>Order detail</h1><p>{customers.find(c => c.id === order.customer_id)?.name} · {new Date(order.created_at).toLocaleString("en-GB")}</p></div><span className="badge approved">Saved · immutable snapshot</span></div><SessionStrip identity={identity} /><div className="snapshot-callout"><div><span>HISTORICAL RATE SNAPSHOT</span><strong>{order.exchange_rate_sdg_per_usd.toLocaleString("en-US")} SDG/USD</strong><p>Captured on this order at save time.</p></div><div><span>CURRENT RATE</span><strong>{rate?.toLocaleString("en-US") || "—"}</strong>{identity.role === "owner" && <button className="text-button" onClick={setTodayRate}>Set today&apos;s rate to 9,000</button>}</div></div>{message && <p className="info-message" role="status">{message}</p>}<div className="detail-grid"><section className="panel detail-lines"><div className="section-head"><span className="step">01</span><div><h2>Order lines</h2><p>Prices and discounts saved with the order.</p></div></div>{order.order_lines.map(line => <div className="detail-line" key={line.id}><div><strong>{products.find(p => p.id === line.product_id)?.name || line.product_id}</strong><small>{line.quantity} × {money(line.unit_price_usd_cents)} · discount {money(line.discount_usd_cents)} ({percent(line.discount_percentage_basis_points)})</small></div><strong>{money(line.line_total_usd_cents)}</strong></div>)}<div className="detail-totals"><div><span>Subtotal</span><strong>{money(order.subtotal_usd_cents)}</strong></div><div><span>Discounts</span><strong>−{money(order.discount_usd_cents)}</strong></div><div><span>Total USD</span><strong>{money(order.total_usd_cents)}</strong></div><div className="final"><span>Total SDG at {order.exchange_rate_sdg_per_usd.toLocaleString("en-US")}</span><strong>{sdg(order.total_sdg)}</strong></div></div></section><aside className="panel activity"><div className="section-head"><span className="step">02</span><div><h2>Activity</h2><p>Database audit events.</p></div></div>{order.audit_events.map((event, i) => <div className="activity-item" key={i}><span className="activity-dot"/><div><strong>{event.event_type.replaceAll("_", " ")}</strong><time>{new Date(event.created_at).toLocaleString("en-GB")}</time></div></div>)}</aside></div></div>;
}
